rvm:
  - 1.8.7
  - 1.9.2
gemfile:
  - gemfiles/Gemfile.rails-2.3
  - gemfiles/Gemfile.rails-3.0
  - gemfiles/Gemfile.rails-3.1
before_script: "rake postgresql:rebuild_databases mysql:rebuild_databases"
after_script: "rake postgresql:drop_databases mysql:drop_databases"
notifications:
  recipients:
    - michal.lomnicki@gmail.com
branches:
  only:
    - travis
