rvm:
  - 1.9.2
  - 1.9.3
gemfile:
  - gemfiles/rails-3.2/Gemfile.postgresql
  - gemfiles/rails-3.2/Gemfile.sqlite3
  - gemfiles/rails-3.2/Gemfile.mysql
  - gemfiles/rails-3.2/Gemfile.mysql2
before_script:
  - rake create_databases
after_script:
  - rake drop_databases
env: 'POSTGRES_DB_USER=postgres MYSQL_DB_USER=""'
notifications:
  recipients:
    - michal.lomnicki@gmail.com
    - ronen@barzel.org
